# -*- coding: utf-8 -*-
"""Analisando Bases: NSL-KDD

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ipTH1Lz002ih8L_m5bJHFtuqD93UC1AQ

# Conhecendo a base
"""

#NSL-KDD
import kagglehub

# Download latest version
path = kagglehub.dataset_download("hassan06/nslkdd")

print("Path to dataset files:", path)

print("Dataset files:")
#!ls -lh $path

print("KDDTest-21.txt")

import pandas as pd
import os

# Caminho base retornado pelo kagglehub
path = kagglehub.dataset_download("hassan06/nslkdd")

# Monta o caminho completo para o arquivo desejado
file_path = os.path.join(path, "KDDTest-21.txt")

# Carrega o dataset
# Nota: Como o NSL-KDD não tem cabeçalho, usamos header=None
df = pd.read_csv(file_path, header=None)

# Ver as primeiras linhas (as colunas aparecerão como 0, 1, 2...)
print(df.head())

import pandas as pd
import os

# Definindo o caminho para o arquivo de treino
file_path = os.path.join(path, 'KDDTrain+.txt')

# Carregando o DataFrame
df = pd.read_csv(file_path, header=None)

# Exibindo as primeiras 5 linhas
#display(df.head())

# Verificando valores únicos nas colunas categóricas principais
print("Valores únicos por coluna categórica:")
print(f"Protocolos (Coluna 1): {df[1].unique()}")
print(f"Flags (Coluna 3): {df[3].unique()}")

# Resumo da coluna de labels (Coluna 41)
print("\nDistribuição das classes (Top 10):")
#display(df[41].value_counts().head(10))

# Resumo estatístico das colunas numéricas
print("\nResumo estatístico das colunas numéricas:")
#display(df.describe())

"""## Teste 1"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB

import os

files = os.listdir(path)
print(files)

train_file = os.path.join(path, "KDDTrain+.txt")

df = pd.read_csv(train_file, header=None)
df.head()

columns = [
'duration','protocol_type','service','flag','src_bytes','dst_bytes',
'land','wrong_fragment','urgent','hot','num_failed_logins',
'logged_in','num_compromised','root_shell','su_attempted','num_root',
'num_file_creations','num_shells','num_access_files','num_outbound_cmds',
'is_host_login','is_guest_login','count','srv_count','serror_rate',
'srv_serror_rate','rerror_rate','srv_rerror_rate','same_srv_rate',
'diff_srv_rate','srv_diff_host_rate','dst_host_count','dst_host_srv_count',
'dst_host_same_srv_rate','dst_host_diff_srv_rate',
'dst_host_same_src_port_rate','dst_host_srv_diff_host_rate',
'dst_host_serror_rate','dst_host_srv_serror_rate',
'dst_host_rerror_rate','dst_host_srv_rerror_rate','label','difficulty'
]

df.columns = columns

# Coluna Inútil
df = df.drop(columns=['difficulty'])

print(df['label'].value_counts())

df['label'].value_counts().plot(kind='bar')
plt.title("Distribuição de ataques")
plt.show()

def map_attack(label):
    if label == 'normal':
        return 'normal'
    elif label in ['neptune','back','land','pod','smurf','teardrop']:
        return 'dos'
    elif label in ['ipsweep','nmap','portsweep','satan']:
        return 'probe'
    elif label in ['ftp_write','guess_passwd','imap','multihop','phf','spy','warezclient','warezmaster']:
        return 'r2l'
    else:
        return 'u2r'

df['label'] = df['label'].apply(map_attack)

from sklearn.preprocessing import LabelEncoder

categorical_cols = ['protocol_type', 'service', 'flag']

le = LabelEncoder()
for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

''' APRENDIZADO SUPERVISIONADO => “Aprenda a prever y usando X”
X (features) = informações da conexão; tudo que o modelo pode usar pra decidir
y (label) = tipo de tráfego (ataque ou normal); a resposta correta
Separamos X e y porque o modelo precisa aprender a prever o resultado (y) com base nas informações (X).'''

X = df.drop('label', axis=1)
y = df['label']

plt.figure(figsize=(12,8))
sns.heatmap(X.corr(), cmap='coolwarm')
plt.title("Matriz de Correlação")
plt.show()

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

plt.scatter(X_pca[:,0], X_pca[:,1], c=pd.factorize(y)[0], cmap='viridis')
plt.title("PCA - Visualização")
plt.show()

import numpy as np

labels = np.unique(y)
colors = plt.cm.viridis(np.linspace(0, 1, len(labels)))

for i, label in enumerate(labels):
    plt.scatter(
        X_pca[y == label, 0],
        X_pca[y == label, 1],
        label=label,
        color=colors[i]
    )

plt.xlabel("Componente Principal 1")
plt.ylabel("Componente Principal 2")
plt.title("PCA - Visualização das Classes")
plt.legend()
plt.show()

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3)

rf = RandomForestClassifier()
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

print("Random Forest")
print(classification_report(y_test, y_pred))

"""## Teste 2"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Colunas do NSL-KDD (41 features + 1 label + 1 difficulty)
colunas = [
    'duration', 'protocol_type', 'service', 'flag', 'src_bytes', 'dst_bytes',
    'land', 'wrong_fragment', 'urgent', 'hot', 'num_failed_logins',
    'logged_in', 'num_compromised', 'root_shell', 'su_attempted', 'num_root',
    'num_file_creations', 'num_shells', 'num_access_files', 'num_outbound_cmds',
    'is_host_login', 'is_guest_login', 'count', 'srv_count', 'serror_rate',
    'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
    'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count',
    'dst_host_same_srv_rate', 'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
    'dst_host_srv_diff_host_rate', 'dst_host_serror_rate', 'dst_host_srv_serror_rate',
    'dst_host_rerror_rate', 'dst_host_srv_rerror_rate', 'label', 'difficulty'
]

# Carregar (ajuste o path)
df = pd.read_csv(os.path.join(path, 'KDDTrain+.txt'), names=colunas)

# Criar target binário: normal (0) ou ataque (1)
df['attack'] = df['label'].apply(lambda x: 0 if x == 'normal' else 1)

# Remover colunas não numéricas para correlação/PCA (guardando service, protocol, flag para depois)
df_numeric = df.select_dtypes(include=[np.number])
df_numeric = df_numeric.drop('difficulty', axis=1, errors='ignore')  # difficulty não ajuda

# Correlação com a variável 'attack'
corr_with_attack = df_numeric.corr()['attack'].sort_values(ascending=False)

print("Top 10 features mais correlacionados com ataques:")
print(corr_with_attack.head(11))  # incluindo ela mesma

# Matriz de correlação geral (opcional, pode ser grande)
plt.figure(figsize=(14, 10))
sns.heatmap(df_numeric.corr(), cmap='coolwarm', center=0, square=True,
            linewidths=0.1, cbar_kws={"shrink": 0.8})
plt.title('Matriz de Correlação - NSL-KDD')
plt.tight_layout()
plt.show()

from sklearn.decomposition import PCA

# Padronizar os dados (PCA é sensível a escala)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_numeric.drop('attack', axis=1))
y = df_numeric['attack'].values

# Aplicar PCA
pca = PCA(n_components=0.95)  # manter 95% da variância
X_pca = pca.fit_transform(X_scaled)

print(f"Dimensão original: {X_scaled.shape[1]} features")
print(f"Dimensão após PCA: {X_pca.shape[1]} componentes")
print(f"Variância explicada acumulada: {np.cumsum(pca.explained_variance_ratio_)[-1]:.2%}")

# Plot variância explicada
plt.figure(figsize=(10, 5))
plt.plot(np.cumsum(pca.explained_variance_ratio_), marker='o')
plt.xlabel('Número de Componentes')
plt.ylabel('Variância Explicada Acumulada')
plt.axhline(y=0.95, color='r', linestyle='--')
plt.grid(True)
plt.title('PCA - Variância Explicada')
plt.show()

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import time

# Usar dados padronizados (sem PCA primeiro, para identificar features importantes)
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)

# Dicionário de modelos
modelos = {
    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1),
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'KNN': KNeighborsClassifier(n_neighbors=5),
    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),
    'SVM (linear)': SVC(kernel='linear', random_state=42)
}

resultados = []

print("="*95)
print(f"{'Modelo':<20} {'Acurácia':<10} {'Precisão':<10} {'Recall':<10} {'F1-Score':<10} {'Tempo treino(s)':<10} {'Tempo teste(s)':<10}")
print("="*95)

for nome, modelo in modelos.items():
    start_train = time.time()
    modelo.fit(X_train, y_train)
    end_train = time.time() # Corrected: Call time.time() to get the timestamp
    start_test = time.time()
    y_pred = modelo.predict(X_test)
    end_test = time.time() # Corrected: Call time.time() to get the timestamp

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    resultados.append({
        'Modelo': nome,
        'Acurácia': acc,
        'Precisão': prec,
        'Recall': rec,
        'F1-Score': f1,
        'Tempo treino(s)': end_train - start_train,
        'tempo teste(s)': end_test - start_test
    })

    print(f"{nome:<20} {acc:<10.4f} {prec:<10.4f} {rec:<10.4f} {f1:<10.4f} {end_train-start_train:<15.4f} {end_test-start_test:<15.4f}")

# Dataframe com resultados
df_resultados = pd.DataFrame(resultados)
print("\nMelhor modelo por F1-Score:")
print(df_resultados.loc[df_resultados['F1-Score'].idxmax()])

"""## Teste 3"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import kagglehub
import os
import time
import warnings
warnings.filterwarnings('ignore')

# Download do dataset NSL-KDD
print("Baixando dataset NSL-KDD...")
path = kagglehub.dataset_download("hassan06/nslkdd")
print(f"Dataset baixado em: {path}")

# Listar arquivos disponíveis
print("\nArquivos disponíveis:")
for file in os.listdir(path):
    print(f"  - {file}")

# Colunas do NSL-KDD (41 features + label + difficulty)
colunas = [
    'duration', 'protocol_type', 'service', 'flag', 'src_bytes', 'dst_bytes',
    'land', 'wrong_fragment', 'urgent', 'hot', 'num_failed_logins',
    'logged_in', 'num_compromised', 'root_shell', 'su_attempted', 'num_root',
    'num_file_creations', 'num_shells', 'num_access_files', 'num_outbound_cmds',
    'is_host_login', 'is_guest_login', 'count', 'srv_count', 'serror_rate',
    'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
    'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count',
    'dst_host_same_srv_rate', 'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
    'dst_host_srv_diff_host_rate', 'dst_host_serror_rate', 'dst_host_srv_serror_rate',
    'dst_host_rerror_rate', 'dst_host_srv_rerror_rate', 'label', 'difficulty'
]

# Carregar KDDTrain+ (treinamento)
print("\nCarregando KDDTrain+.txt...")
train_file = os.path.join(path, 'KDDTrain+.txt')
df_train = pd.read_csv(train_file, names=colunas)

# Carregar KDDTest+ (teste - opcional, para validação final)
print("Carregando KDDTest+.txt...")
test_file = os.path.join(path, 'KDDTest+.txt')
df_test = pd.read_csv(test_file, names=colunas)

print(f"\nShape treino: {df_train.shape}")
print(f"Shape teste: {df_test.shape}")

# Criar target binário: normal (0) ou ataque (1)
df_train['attack'] = df_train['label'].apply(lambda x: 0 if x == 'normal' else 1)
df_test['attack'] = df_test['label'].apply(lambda x: 0 if x == 'normal' else 1)

# Ver distribuição das classes
print("\nDistribuição das classes (treino):")
print(df_train['attack'].value_counts())
print(f"Normal: {df_train['attack'].value_counts()[0]} ({df_train['attack'].value_counts()[0]/len(df_train)*100:.2f}%)")
print(f"Ataque: {df_train['attack'].value_counts()[1]} ({df_train['attack'].value_counts()[1]/len(df_train)*100:.2f}%)")

# Selecionar apenas colunas numéricas
df_train_numeric = df_train.select_dtypes(include=[np.number])
df_train_numeric = df_train_numeric.drop('difficulty', axis=1, errors='ignore')

# Correlação com a variável 'attack'
corr_with_attack = df_train_numeric.corr()['attack'].sort_values(ascending=False)

print("\n" + "="*60)
print("TOP 10 FEATURES MAIS CORRELACIONADAS COM ATAQUES:")
print("="*60)
for i, (feature, corr) in enumerate(corr_with_attack.head(11).items(), 1):
    if feature != 'attack':
        print(f"{i:2d}. {feature:35s} {corr:+.4f}")

print("\n" + "="*60)
print("TOP 10 FEATURES MENOS CORRELACIONADAS (ou anti-correlacionadas):")
print("="*60)
for i, (feature, corr) in enumerate(corr_with_attack.tail(10).items(), 1):
    print(f"{i:2d}. {feature:35s} {corr:+.4f}")

# Heatmap das top 20 features correlacionadas com o ataque
top_features = corr_with_attack.head(21).index.tolist()  # incluindo 'attack'
plt.figure(figsize=(12, 10))
sns.heatmap(df_train_numeric[top_features].corr(),
            cmap='coolwarm', center=0,
            annot=True, fmt='.2f',
            square=True,
            linewidths=0.5,
            cbar_kws={"shrink": 0.8})
plt.title('Matriz de Correlação - Top 20 Features (incluindo target)')
plt.tight_layout()
plt.show()

# Preparar dados para PCA (apenas features numéricas, sem target)
X = df_train_numeric.drop('attack', axis=1)
y = df_train['attack'].values

# Padronizar (PCA é sensível a escala)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Aplicar PCA
print("\n" + "="*60)
print("ANÁLISE DE PCA:")
print("="*60)

# PCA com 95% da variância
pca_95 = PCA(n_components=0.95)
X_pca_95 = pca_95.fit_transform(X_scaled)

print(f"Dimensão original: {X_scaled.shape[1]} features")
print(f"Dimensão após PCA (95% variância): {X_pca_95.shape[1]} componentes")
print(f"Variância explicada acumulada: {np.cumsum(pca_95.explained_variance_ratio_)[-1]:.2%}")

# PCA com componentes fixos (para visualização 2D)
pca_2d = PCA(n_components=2)
X_pca_2d = pca_2d.fit_transform(X_scaled)

# Plot 2D PCA colorido por classe
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.scatter(X_pca_2d[y==0, 0], X_pca_2d[y==0, 1], c='blue', alpha=0.5, s=1, label='Normal')
plt.scatter(X_pca_2d[y==1, 0], X_pca_2d[y==1, 1], c='red', alpha=0.5, s=1, label='Ataque')
plt.xlabel('Primeira Componente Principal')
plt.ylabel('Segunda Componente Principal')
plt.title('PCA 2D - NSL-KDD')
plt.legend()
plt.grid(True, alpha=0.3)

# Variância explicada acumulada
plt.subplot(1, 2, 2)
cumulative_variance = np.cumsum(pca_95.explained_variance_ratio_)
plt.plot(range(1, len(cumulative_variance)+1), cumulative_variance, 'bo-', linewidth=2)
plt.axhline(y=0.95, color='r', linestyle='--', label='95% variância')
plt.xlabel('Número de Componentes')
plt.ylabel('Variância Explicada Acumulada')
plt.title('PCA - Variância Explicada Acumulada')
plt.grid(True, alpha=0.3)
plt.legend()

plt.tight_layout()
plt.show()

print(f"\nPara manter 95% da variância, você precisa de {pca_95.n_components_} componentes")

# Usar dados padronizados (X_scaled já criado)
X_train, X_val, y_train, y_val = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)

# Dicionário de modelos
modelos = {
    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1),
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'KNN (k=5)': KNeighborsClassifier(n_neighbors=5),
    'KNN (k=3)': KNeighborsClassifier(n_neighbors=3),
    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),
    'SVM (linear)': SVC(kernel='linear', random_state=42)
}

resultados = []

print("\n" + "="*80)
print(f"{'Modelo':<20} {'Acurácia':<10} {'Precisão':<10} {'Recall':<10} {'F1-Score':<10} {'Tempo treino(s)':<10}")
print("="*80)

for nome, modelo in modelos.items():
    start = time.time()
    modelo.fit(X_train, y_train)
    y_pred = modelo.predict(X_val)
    end = time.time()

    acc = accuracy_score(y_val, y_pred)
    prec = precision_score(y_val, y_pred)
    rec = recall_score(y_val, y_pred)
    f1 = f1_score(y_val, y_pred)

    resultados.append({
        'Modelo': nome,
        'Acurácia': acc,
        'Precisão': prec,
        'Recall': rec,
        'F1-Score': f1,
        'Tempo treino(s)': end - start
    })

    print(f"{nome:<20} {acc:<10.4f} {prec:<10.4f} {rec:<10.4f} {f1:<10.4f} {end-start:<15.4f}")

# Dataframe com resultados
df_resultados = pd.DataFrame(resultados)
df_resultados = df_resultados.sort_values('F1-Score', ascending=False)

print("\n" + "="*60)
print("RANKING DOS MODELOS (por F1-Score):")
print("="*60)
print(df_resultados.to_string(index=False))

# Gráfico comparativo
plt.figure(figsize=(12, 6))
df_resultados_melted = df_resultados.melt(id_vars=['Modelo'],
                                          value_vars=['Acurácia', 'Precisão', 'Recall', 'F1-Score'],
                                          var_name='Métrica',
                                          value_name='Valor')
sns.barplot(data=df_resultados_melted, x='Modelo', y='Valor', hue='Métrica')
plt.title('Comparação de Desempenho dos Modelos')
plt.xticks(rotation=45, ha='right')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

# Treinar Random Forest novamente para extrair importância
rf = DecisionTreeClassifier(random_state=42)
rf.fit(X_scaled, y)

# Criar dataframe de importância
feature_names = X.columns
importances = pd.DataFrame({
    'feature': feature_names,
    'importance': rf.feature_importances_
}).sort_values('importance', ascending=False)

print("\n" + "="*60)
print("TOP 20 FEATURES MAIS IMPORTANTES (Decision Tree):")
print("="*60)
for i, row in importances.head(20).iterrows():
    print(f"{i+1:2d}. {row['feature']:35s} {row['importance']:.4f}")

# Plot
fig, axes = plt.subplots(1, 2, figsize=(14, 8))

# Top 20 features
sns.barplot(data=importances.head(20), x='importance', y='feature', ax=axes[0])
axes[0].set_title('Top 20 Features - Decision Tree')
axes[0].set_xlabel('Importância')

# Importância acumulada
cumulative_importance = importances['importance'].cumsum()
axes[1].plot(range(1, len(cumulative_importance)+1), cumulative_importance, 'go-', linewidth=2)
axes[1].axhline(y=0.8, color='r', linestyle='--', label='80%')
axes[1].axhline(y=0.9, color='orange', linestyle='--', label='90%')
axes[1].set_xlabel('Número de Features')
axes[1].set_ylabel('Importância Acumulada')
axes[1].set_title('Importância Acumulada das Features')
axes[1].grid(True, alpha=0.3)
axes[1].legend()

# Encontrar quantas features chegam a 80% e 90%
n_80 = (cumulative_importance <= 0.8).sum() + 1
n_90 = (cumulative_importance <= 0.9).sum() + 1
axes[1].axvline(x=n_80, color='r', linestyle=':', alpha=0.5)
axes[1].axvline(x=n_90, color='orange', linestyle=':', alpha=0.5)
axes[1].text(n_80, 0.80, f'{n_80} features\n(80%)', ha='center')
axes[1].text(n_90, 0.90, f'{n_90} features\n(90%)', ha='center')

plt.tight_layout()
plt.show()

print(f"\nCom as top {n_80} features você atinge 80% da importância")
print(f"Com as top {n_90} features você atinge 90% da importância")

# Preparar dados de teste
df_test_numeric = df_test.select_dtypes(include=[np.number])
df_test_numeric = df_test_numeric.drop('difficulty', axis=1, errors='ignore')
X_test_original = df_test_numeric.drop('attack', axis=1)
y_test = df_test['attack'].values

# Padronizar usando o scaler do treino
X_test_scaled = scaler.transform(X_test_original)

# Validar melhor modelo no conjunto de teste
melhor_modelo_nome = df_resultados.iloc[0]['Modelo']
melhor_modelo = None

for nome, modelo in modelos.items():
    if nome == melhor_modelo_nome:
        melhor_modelo = modelo
        break

if melhor_modelo:
    # Re-treinar no treino completo
    melhor_modelo.fit(X_scaled, y)
    y_pred_test = melhor_modelo.predict(X_test_scaled)

    print("\n" + "="*60)
    print(f"VALIDAÇÃO NO KDDTest+ COM {melhor_modelo_nome}:")
    print("="*60)
    print(f"Acurácia:  {accuracy_score(y_test, y_pred_test):.4f}")
    print(f"Precisão:  {precision_score(y_test, y_pred_test):.4f}")
    print(f"Recall:    {recall_score(y_test, y_pred_test):.4f}")
    print(f"F1-Score:  {f1_score(y_test, y_pred_test):.4f}")

    # Matriz de confusão
    cm = confusion_matrix(y_test, y_pred_test)
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=['Normal', 'Ataque'],
                yticklabels=['Normal', 'Ataque'])
    plt.title(f'Matriz de Confusão - {melhor_modelo_nome}')
    plt.ylabel('Real')
    plt.xlabel('Predito')
    plt.show()

# Treinar Random Forest novamente para extrair importância
rf = DecisionTreeClassifier(random_state=42)
rf.fit(X_scaled, y)

# Criar dataframe de importância
feature_names = X.columns
importances = pd.DataFrame({
    'feature': feature_names,
    'importance': rf.feature_importances_
}).sort_values('importance', ascending=False)

print("\n" + "="*60)
print("TOP 20 FEATURES MAIS IMPORTANTES (Random Forest):")
print("="*60)
for i, row in importances.head(20).iterrows():
    print(f"{i+1:2d}. {row['feature']:35s} {row['importance']:.4f}")

# Plot
fig, axes = plt.subplots(1, 2, figsize=(14, 8))

# Top 20 features
sns.barplot(data=importances.head(20), x='importance', y='feature', ax=axes[0])
axes[0].set_title('Top 20 Features - Random Forest')
axes[0].set_xlabel('Importância')

# Importância acumulada
cumulative_importance = importances['importance'].cumsum()
axes[1].plot(range(1, len(cumulative_importance)+1), cumulative_importance, 'go-', linewidth=2)
axes[1].axhline(y=0.8, color='r', linestyle='--', label='80%')
axes[1].axhline(y=0.9, color='orange', linestyle='--', label='90%')
axes[1].set_xlabel('Número de Features')
axes[1].set_ylabel('Importância Acumulada')
axes[1].set_title('Importância Acumulada das Features')
axes[1].grid(True, alpha=0.3)
axes[1].legend()

# Encontrar quantas features chegam a 80% e 90%
n_80 = (cumulative_importance <= 0.8).sum() + 1
n_90 = (cumulative_importance <= 0.9).sum() + 1
axes[1].axvline(x=n_80, color='r', linestyle=':', alpha=0.5)
axes[1].axvline(x=n_90, color='orange', linestyle=':', alpha=0.5)
axes[1].text(n_80, 0.85, f'{n_80} features\n(80%)', ha='center')
axes[1].text(n_90, 0.95, f'{n_90} features\n(90%)', ha='center')

plt.tight_layout()
plt.show()

print(f"\nCom as top {n_80} features você atinge 80% da importância")
print(f"Com as top {n_90} features você atinge 90% da importância")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score # Alterado de f1_score para accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

# Certifique-se de que X_scaled, y e 'importances' (do Random Forest) estejam disponíveis
# 'importances' foi calculado no Teste 3, célula N831OsMCHmx8

if 'importances' not in globals():
    print("Variável 'importances' não encontrada. Execute as células anteriores.")
    # Recriar importances para garantir que o código seja executável se for rodado isoladamente
    # (Este é um fallback, o ideal é que o notebook seja executado em ordem)
    try:
        rf_temp = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
        rf_temp.fit(X_scaled, y)
        feature_names = X.columns
        importances = pd.DataFrame({
            'feature': feature_names,
            'importance': rf_temp.feature_importances_
        }).sort_values('importance', ascending=False)
    except Exception as e:
        print(f"Erro ao recriar importances: {e}. Verifique se X_scaled e y estão definidos.")
        exit()

# Armazenar os resultados
results = []

# Loop para testar de 5 a 38 features
for n_features in range(5, 39):
    # Selecionar as top n_features com base na importância
    top_features_names = importances['feature'].head(n_features).tolist()
    # Obter os índices das colunas no DataFrame original (X) para X_scaled
    feature_indices = [X.columns.get_loc(col) for col in top_features_names]

    X_selected = X_scaled[:, feature_indices]

    # Dividir os dados em treino e teste
    X_train_nf, X_test_nf, y_train_nf, y_test_nf = train_test_split(
        X_selected, y, test_size=0.2, random_state=42, stratify=y
    )

    # Treinar o modelo Decision Tree
    dt_model = DecisionTreeClassifier(random_state=42)
    dt_model.fit(X_train_nf, y_train_nf)

    # Fazer previsões e calcular a acurácia
    y_pred_nf = dt_model.predict(X_test_nf)
    accuracy = accuracy_score(y_test_nf, y_pred_nf) # Alterado de f1 para accuracy

    results.append({'n_features': n_features, 'accuracy_score': accuracy}) # Alterado de f1_score para accuracy_score

# Converter resultados para DataFrame para visualização
df_results = pd.DataFrame(results)

print("\n" + "="*60)
print("DESEMPENHO DA DECISION TREE COM DIFERENTES NÚMEROS DE FEATURES")
print("="*60)
print(df_results.to_string(index=False))

# Plotar os resultados
plt.figure(figsize=(12, 6))
sns.lineplot(data=df_results, x='n_features', y='accuracy_score', marker='o') # Alterado de f1_score para accuracy_score
plt.title('Acurácia da Decision Tree vs. Número de Features') # Alterado de F1-Score para Acurácia
plt.xlabel('Número de Features')
plt.ylabel('Acurácia') # Alterado de F1-Score para Acurácia
plt.grid(True, linestyle='--', alpha=0.7)
plt.xticks(range(5, 39, 1)) # Mostrar todos os números de features no eixo X
plt.tight_layout()
plt.show()

# Encontrar o número de features com a maior acurácia
best_performance = df_results.loc[df_results['accuracy_score'].idxmax()] # Alterado de f1_score para accuracy_score
print(f"\nMelhor Acurácia: {best_performance['accuracy_score']:.4f} com {int(best_performance['n_features'])} features.") # Alterado de F1-Score para Acurácia

print("\n" + "="*60)
print("AS TOP 18 FEATURES COM MAIOR IMPORTÂNCIA:")
print("="*60)

top_24_features = importances['feature'].head(18).tolist()
for i, feature_name in enumerate(top_24_features):
    print(f"{i+1:2d}. {feature_name}")

"""## Teste 4"""
# Execute esta célula no seu notebook
# DEPOIS de ter treinado o modelo Decision Tree

import pickle
import json
import os
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder

# 1. Recrie os LabelEncoders para cada coluna categórica
# (Use os mesmos encoders que você usou no notebook)
from sklearn.preprocessing import LabelEncoder

# Recriar encoders específicos para cada coluna
# (Assumindo que você já tem os dados no df)
le_protocol = LabelEncoder()
le_protocol.fit(df['protocol_type'])

le_service = LabelEncoder()
le_service.fit(df['service'])

le_flag = LabelEncoder()
le_flag.fit(df['flag'])

categorical_encoders = {
    'protocol_type': le_protocol,
    'service': le_service,
    'flag': le_flag
}

# 2. Criar diretório models
model_dir = './models'
os.makedirs(model_dir, exist_ok=True)

# 3. Salvar modelo Decision Tree (use o modelo que você treinou)
# Se você não tem o modelo salvo, treine novamente:
# dt_model = DecisionTreeClassifier(random_state=42)
# dt_model.fit(X_scaled, y)

with open(f'{model_dir}/decision_tree_model.pkl', 'wb') as f:
    pickle.dump(dt_model, f)
print(f"✅ Modelo salvo: {model_dir}/decision_tree_model.pkl")

# 4. Salvar StandardScaler
# Use o scaler que você já criou no notebook
# X_scaled = scaler.fit_transform(X)
with open(f'{model_dir}/scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)
print(f"✅ Scaler salvo: {model_dir}/scaler.pkl")

# 5. Salvar LabelEncoders
for name, encoder in categorical_encoders.items():
    with open(f'{model_dir}/label_encoder_{name}.pkl', 'wb') as f:
        pickle.dump(encoder, f)
    print(f"✅ Encoder salvo: label_encoder_{name}.pkl")

# 6. Salvar features selecionadas (as 18 do seu MVP1)
selected_features = [
    'src_bytes', 'dst_host_srv_count', 'count', 'dst_bytes',
    'dst_host_srv_terror_rate', 'hot', 'dst_host_same_src_port_rate',
    'logged_in', 'srv_count', 'dst_host_same_srv_rate',
    'duration', 'wrong_fragment', 'dst_host_terror_rate',
    'dst_host_diff_srv_rate', 'dst_host_count',
    'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
    'diff_srv_rate'
]

with open(f'{model_dir}/selected_features.json', 'w') as f:
    json.dump(selected_features, f)
print(f"✅ Features selecionadas salvas: {len(selected_features)} features")

print("\n" + "="*50)
print("🎯 TODOS OS ARTEFATOS FORAM SALVOS COM SUCESSO!")
print("="*50)
print(f"📁 Diretório: {model_dir}")
print(f"📊 Features: {len(selected_features)}")
print(f"🤖 Modelo: {type(dt_model).__name__}")