# -*- coding: utf-8 -*-
"""Analisando Bases: NSL-KDD

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ipTH1Lz002ih8L_m5bJHFtuqD93UC1AQ

# Conhecendo a base
"""

#NSL-KDD
import kagglehub

# Download latest version
path = kagglehub.dataset_download("hassan06/nslkdd")

print("Path to dataset files:", path)

print("Dataset files:")

print("KDDTest-21.txt")

import pandas as pd
import os

# Caminho base retornado pelo kagglehub
path = kagglehub.dataset_download("hassan06/nslkdd")

# Monta o caminho completo para o arquivo desejado
file_path = os.path.join(path, "KDDTest-21.txt")

# Carrega o dataset
# Nota: Como o NSL-KDD não tem cabeçalho, usamos header=None
df = pd.read_csv(file_path, header=None)

# Ver as primeiras linhas (as colunas aparecerão como 0, 1, 2...)
print(df.head())

import pandas as pd
import os

# Definindo o caminho para o arquivo de treino
file_path = os.path.join(path, 'KDDTrain+.txt')

# Carregando o DataFrame
df = pd.read_csv(file_path, header=None)

# Exibindo as primeiras 5 linhas
# display(df.head())

# Verificando valores únicos nas colunas categóricas principais
print("Valores únicos por coluna categórica:")
print(f"Protocolos (Coluna 1): {df[1].unique()}")
print(f"Flags (Coluna 3): {df[3].unique()}")

# Resumo da coluna de labels (Coluna 41)
print("\nDistribuição das classes (Top 10):")
# display(df[41].value_counts().head(10))

# Resumo estatístico das colunas numéricas
print("\nResumo estatístico das colunas numéricas:")
# display(df.describe())

"""## Teste 1"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB

import os

files = os.listdir(path)
print(files)

train_file = os.path.join(path, "KDDTrain+.txt")

df = pd.read_csv(train_file, header=None)
df.head()

columns = [
'duration','protocol_type','service','flag','src_bytes','dst_bytes',
'land','wrong_fragment','urgent','hot','num_failed_logins',
'logged_in','num_compromised','root_shell','su_attempted','num_root',
'num_file_creations','num_shells','num_access_files','num_outbound_cmds',
'is_host_login','is_guest_login','count','srv_count','serror_rate',
'srv_serror_rate','rerror_rate','srv_rerror_rate','same_srv_rate',
'diff_srv_rate','srv_diff_host_rate','dst_host_count','dst_host_srv_count',
'dst_host_same_srv_rate','dst_host_diff_srv_rate',
'dst_host_same_src_port_rate','dst_host_srv_diff_host_rate',
'dst_host_serror_rate','dst_host_srv_serror_rate',
'dst_host_rerror_rate','dst_host_srv_rerror_rate','label','difficulty'
]

df.columns = columns

# Coluna Inútil
df = df.drop(columns=['difficulty'])

print(df['label'].value_counts())

df['label'].value_counts().plot(kind='bar')
plt.title("Distribuição de ataques")
plt.show()

def map_attack(label):
    if label == 'normal':
        return 'normal'
    elif label in ['neptune','back','land','pod','smurf','teardrop']:
        return 'dos'
    elif label in ['ipsweep','nmap','portsweep','satan']:
        return 'probe'
    elif label in ['ftp_write','guess_passwd','imap','multihop','phf','spy','warezclient','warezmaster']:
        return 'r2l'
    else:
        return 'u2r'

df['label'] = df['label'].apply(map_attack)

from sklearn.preprocessing import LabelEncoder

categorical_cols = ['protocol_type', 'service', 'flag']

le = LabelEncoder()
for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

''' APRENDIZADO SUPERVISIONADO => “Aprenda a prever y usando X”
X (features) = informações da conexão; tudo que o modelo pode usar pra decidir
y (label) = tipo de tráfego (ataque ou normal); a resposta correta
Separamos X e y porque o modelo precisa aprender a prever o resultado (y) com base nas informações (X).'''

X = df.drop('label', axis=1)
y = df['label']

plt.figure(figsize=(12,8))
sns.heatmap(X.corr(), cmap='coolwarm')
plt.title("Matriz de Correlação")
plt.show()

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=3)
X_pca = pca.fit_transform(X_scaled)

# plt.scatter(X_pca[:,0], X_pca[:,1], c=pd.factorize(y)[0], cmap='viridis')
# plt.title("PCA - Visualização")
# plt.show()
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

scatter = ax.scatter(
    X_pca[:,0],
    X_pca[:,1],
    X_pca[:,2],
    c=pd.factorize(y)[0],
    cmap='viridis'
)

ax.set_title("PCA - Visualização 3D")
ax.set_xlabel("PC1")
ax.set_ylabel("PC2")
ax.set_zlabel("PC3")

plt.show()

import numpy as np

labels = np.unique(y)
colors = plt.cm.viridis(np.linspace(0, 1, len(labels)))

for i, label in enumerate(labels):
    plt.scatter(
        X_pca[y == label, 0],
        X_pca[y == label, 1],
        label=label,
        color=colors[i]
    )

plt.xlabel("Componente Principal 1")
plt.ylabel("Componente Principal 2")
plt.title("PCA - Visualização das Classes")
plt.legend()
plt.show()

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3)

rf = RandomForestClassifier()
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

print("Random Forest")
print(classification_report(y_test, y_pred))

"""## Teste 2"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Colunas do NSL-KDD (41 features + 1 label + 1 difficulty)
colunas = [
    'duration', 'protocol_type', 'service', 'flag', 'src_bytes', 'dst_bytes',
    'land', 'wrong_fragment', 'urgent', 'hot', 'num_failed_logins',
    'logged_in', 'num_compromised', 'root_shell', 'su_attempted', 'num_root',
    'num_file_creations', 'num_shells', 'num_access_files', 'num_outbound_cmds',
    'is_host_login', 'is_guest_login', 'count', 'srv_count', 'serror_rate',
    'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
    'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count',
    'dst_host_same_srv_rate', 'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
    'dst_host_srv_diff_host_rate', 'dst_host_serror_rate', 'dst_host_srv_serror_rate',
    'dst_host_rerror_rate', 'dst_host_srv_rerror_rate', 'label', 'difficulty'
]

# Carregar (ajuste o path)
df = pd.read_csv(os.path.join(path, 'KDDTrain+.txt'), names=colunas)

# Criar target binário: normal (0) ou ataque (1)
df['attack'] = df['label'].apply(lambda x: 0 if x == 'normal' else 1)

# Remover colunas não numéricas para correlação/PCA (guardando service, protocol, flag para depois)
df_numeric = df.select_dtypes(include=[np.number])
df_numeric = df_numeric.drop('difficulty', axis=1, errors='ignore')  # difficulty não ajuda

# Correlação com a variável 'attack'
corr_with_attack = df_numeric.corr()['attack'].sort_values(ascending=False)

print("Top 10 features mais correlacionados com ataques:")
print(corr_with_attack.head(11))  # incluindo ela mesma

# Matriz de correlação geral (opcional, pode ser grande)
plt.figure(figsize=(14, 10))
sns.heatmap(df_numeric.corr(), cmap='coolwarm', center=0, square=True,
            linewidths=0.1, cbar_kws={"shrink": 0.8})
plt.title('Matriz de Correlação - NSL-KDD')
plt.tight_layout()
plt.show()

from sklearn.decomposition import PCA

# Padronizar os dados (PCA é sensível a escala)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_numeric.drop('attack', axis=1))
y = df_numeric['attack'].values

# Aplicar PCA
pca = PCA(n_components=0.95)  # manter 95% da variância
X_pca = pca.fit_transform(X_scaled)

print(f"Dimensão original: {X_scaled.shape[1]} features")
print(f"Dimensão após PCA: {X_pca.shape[1]} componentes")
print(f"Variância explicada acumulada: {np.cumsum(pca.explained_variance_ratio_)[-1]:.2%}")

# Plot variância explicada
plt.figure(figsize=(10, 5))
plt.plot(np.cumsum(pca.explained_variance_ratio_), marker='o')
plt.xlabel('Número de Componentes')
plt.ylabel('Variância Explicada Acumulada')
plt.axhline(y=0.95, color='r', linestyle='--')
plt.grid(True)
plt.title('PCA - Variância Explicada')
plt.show()

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import time

# Usar dados padronizados (sem PCA primeiro, para identificar features importantes)
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)

# Dicionário de modelos
modelos = {
    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1),
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'KNN': KNeighborsClassifier(n_neighbors=5),
    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),
    'SVM (linear)': SVC(kernel='linear', random_state=42)
}

resultados = []

print("="*95)
print(f"{'Modelo':<20} {'Acurácia':<10} {'Precisão':<10} {'Recall':<10} {'F1-Score':<10} {'Tempo treino(s)':<10} {'Tempo teste(s)':<10}")
print("="*95)

for nome, modelo in modelos.items():
    start_train = time.time()
    modelo.fit(X_train, y_train)
    end_train = time.time() # Corrected: Call time.time() to get the timestamp
    start_test = time.time()
    y_pred = modelo.predict(X_test)
    end_test = time.time() # Corrected: Call time.time() to get the timestamp

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    resultados.append({
        'Modelo': nome,
        'Acurácia': acc,
        'Precisão': prec,
        'Recall': rec,
        'F1-Score': f1,
        'Tempo treino(s)': end_train - start_train,
        'tempo teste(s)': end_test - start_test
    })

    print(f"{nome:<20} {acc:<10.4f} {prec:<10.4f} {rec:<10.4f} {f1:<10.4f} {end_train-start_train:<15.4f} {end_test-start_test:<15.4f}")

# Dataframe com resultados
df_resultados = pd.DataFrame(resultados)
print("\nMelhor modelo por F1-Score:")
print(df_resultados.loc[df_resultados['F1-Score'].idxmax()])

"""## Teste 3"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import kagglehub
import os
import time
import warnings
warnings.filterwarnings('ignore')

# Download do dataset NSL-KDD
print("Baixando dataset NSL-KDD...")
path = kagglehub.dataset_download("hassan06/nslkdd")
print(f"Dataset baixado em: {path}")

# Listar arquivos disponíveis
print("\nArquivos disponíveis:")
for file in os.listdir(path):
    print(f"  - {file}")

# Colunas do NSL-KDD (41 features + label + difficulty)
colunas = [
    'duration', 'protocol_type', 'service', 'flag', 'src_bytes', 'dst_bytes',
    'land', 'wrong_fragment', 'urgent', 'hot', 'num_failed_logins',
    'logged_in', 'num_compromised', 'root_shell', 'su_attempted', 'num_root',
    'num_file_creations', 'num_shells', 'num_access_files', 'num_outbound_cmds',
    'is_host_login', 'is_guest_login', 'count', 'srv_count', 'serror_rate',
    'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
    'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count',
    'dst_host_same_srv_rate', 'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
    'dst_host_srv_diff_host_rate', 'dst_host_serror_rate', 'dst_host_srv_serror_rate',
    'dst_host_rerror_rate', 'dst_host_srv_rerror_rate', 'label', 'difficulty'
]

# Carregar KDDTrain+ (treinamento)
print("\nCarregando KDDTrain+.txt...")
train_file = os.path.join(path, 'KDDTrain+.txt')
df_train = pd.read_csv(train_file, names=colunas)

# Carregar KDDTest+ (teste - opcional, para validação final)
print("Carregando KDDTest+.txt...")
test_file = os.path.join(path, 'KDDTest+.txt')
df_test = pd.read_csv(test_file, names=colunas)

print(f"\nShape treino: {df_train.shape}")
print(f"Shape teste: {df_test.shape}")

# Criar target binário: normal (0) ou ataque (1)
df_train['attack'] = df_train['label'].apply(lambda x: 0 if x == 'normal' else 1)
df_test['attack'] = df_test['label'].apply(lambda x: 0 if x == 'normal' else 1)

# Ver distribuição das classes
print("\nDistribuição das classes (treino):")
print(df_train['attack'].value_counts())
print(f"Normal: {df_train['attack'].value_counts()[0]} ({df_train['attack'].value_counts()[0]/len(df_train)*100:.2f}%)")
print(f"Ataque: {df_train['attack'].value_counts()[1]} ({df_train['attack'].value_counts()[1]/len(df_train)*100:.2f}%)")

# Selecionar apenas colunas numéricas
df_train_numeric = df_train.select_dtypes(include=[np.number])
df_train_numeric = df_train_numeric.drop('difficulty', axis=1, errors='ignore')

# Correlação com a variável 'attack'
corr_with_attack = df_train_numeric.corr()['attack'].sort_values(ascending=False)

print("\n" + "="*60)
print("TOP 10 FEATURES MAIS CORRELACIONADAS COM ATAQUES:")
print("="*60)
for i, (feature, corr) in enumerate(corr_with_attack.head(11).items(), 1):
    if feature != 'attack':
        print(f"{i:2d}. {feature:35s} {corr:+.4f}")

print("\n" + "="*60)
print("TOP 10 FEATURES MENOS CORRELACIONADAS (ou anti-correlacionadas):")
print("="*60)
for i, (feature, corr) in enumerate(corr_with_attack.tail(10).items(), 1):
    print(f"{i:2d}. {feature:35s} {corr:+.4f}")

# Heatmap das top 20 features correlacionadas com o ataque
top_features = corr_with_attack.head(21).index.tolist()  # incluindo 'attack'
plt.figure(figsize=(12, 10))
sns.heatmap(df_train_numeric[top_features].corr(),
            cmap='coolwarm', center=0,
            annot=True, fmt='.2f',
            square=True,
            linewidths=0.5,
            cbar_kws={"shrink": 0.8})
plt.title('Matriz de Correlação - Top 20 Features (incluindo target)')
plt.tight_layout()
plt.show()

# Preparar dados para PCA (apenas features numéricas, sem target)
X = df_train_numeric.drop('attack', axis=1)
y = df_train['attack'].values

# Padronizar (PCA é sensível a escala)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Aplicar PCA
print("\n" + "="*60)
print("ANÁLISE DE PCA:")
print("="*60)

# PCA com 95% da variância
pca_95 = PCA(n_components=0.95)
X_pca_95 = pca_95.fit_transform(X_scaled)

print(f"Dimensão original: {X_scaled.shape[1]} features")
print(f"Dimensão após PCA (95% variância): {X_pca_95.shape[1]} componentes")
print(f"Variância explicada acumulada: {np.cumsum(pca_95.explained_variance_ratio_)[-1]:.2%}")

# PCA com componentes fixos (para visualização 2D)
pca_2d = PCA(n_components=2)
X_pca_2d = pca_2d.fit_transform(X_scaled)

# Plot 2D PCA colorido por classe
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.scatter(X_pca_2d[y==0, 0], X_pca_2d[y==0, 1], c='blue', alpha=0.5, s=1, label='Normal')
plt.scatter(X_pca_2d[y==1, 0], X_pca_2d[y==1, 1], c='red', alpha=0.5, s=1, label='Ataque')
plt.xlabel('Primeira Componente Principal')
plt.ylabel('Segunda Componente Principal')
plt.title('PCA 2D - NSL-KDD')
plt.legend()
plt.grid(True, alpha=0.3)

# Variância explicada acumulada
plt.subplot(1, 2, 2)
cumulative_variance = np.cumsum(pca_95.explained_variance_ratio_)
plt.plot(range(1, len(cumulative_variance)+1), cumulative_variance, 'bo-', linewidth=2)
plt.axhline(y=0.95, color='r', linestyle='--', label='95% variância')
plt.xlabel('Número de Componentes')
plt.ylabel('Variância Explicada Acumulada')
plt.title('PCA - Variância Explicada Acumulada')
plt.grid(True, alpha=0.3)
plt.legend()

plt.tight_layout()
plt.show()

print(f"\nPara manter 95% da variância, você precisa de {pca_95.n_components_} componentes")

# Usar dados padronizados (X_scaled já criado)
X_train, X_val, y_train, y_val = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)

# Dicionário de modelos
modelos = {
    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1),
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'KNN (k=5)': KNeighborsClassifier(n_neighbors=5),
    'KNN (k=3)': KNeighborsClassifier(n_neighbors=3),
    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),
    'SVM (linear)': SVC(kernel='linear', random_state=42)
}

resultados = []

print("\n" + "="*80)
print(f"{'Modelo':<20} {'Acurácia':<10} {'Precisão':<10} {'Recall':<10} {'F1-Score':<10} {'Tempo treino(s)':<10}")
print("="*80)

for nome, modelo in modelos.items():
    start = time.time()
    modelo.fit(X_train, y_train)
    y_pred = modelo.predict(X_val)
    end = time.time()

    acc = accuracy_score(y_val, y_pred)
    prec = precision_score(y_val, y_pred)
    rec = recall_score(y_val, y_pred)
    f1 = f1_score(y_val, y_pred)

    resultados.append({
        'Modelo': nome,
        'Acurácia': acc,
        'Precisão': prec,
        'Recall': rec,
        'F1-Score': f1,
        'Tempo treino(s)': end - start
    })

    print(f"{nome:<20} {acc:<10.4f} {prec:<10.4f} {rec:<10.4f} {f1:<10.4f} {end-start:<15.4f}")

# Dataframe com resultados
df_resultados = pd.DataFrame(resultados)
df_resultados = df_resultados.sort_values('F1-Score', ascending=False)

print("\n" + "="*60)
print("RANKING DOS MODELOS (por F1-Score):")
print("="*60)
print(df_resultados.to_string(index=False))

# Gráfico comparativo
plt.figure(figsize=(12, 6))
df_resultados_melted = df_resultados.melt(id_vars=['Modelo'],
                                          value_vars=['Acurácia', 'Precisão', 'Recall', 'F1-Score'],
                                          var_name='Métrica',
                                          value_name='Valor')
sns.barplot(data=df_resultados_melted, x='Modelo', y='Valor', hue='Métrica')
plt.title('Comparação de Desempenho dos Modelos')
plt.xticks(rotation=45, ha='right')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

# Treinar Random Forest novamente para extrair importância
rf = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
rf.fit(X_scaled, y)

# Criar dataframe de importância
feature_names = X.columns
importances = pd.DataFrame({
    'feature': feature_names,
    'importance': rf.feature_importances_
}).sort_values('importance', ascending=False)

print("\n" + "="*60)
print("TOP 20 FEATURES MAIS IMPORTANTES (Random Forest):")
print("="*60)
for i, row in importances.head(20).iterrows():
    print(f"{i+1:2d}. {row['feature']:35s} {row['importance']:.4f}")

# Plot
fig, axes = plt.subplots(1, 2, figsize=(14, 8))

# Top 20 features
sns.barplot(data=importances.head(20), x='importance', y='feature', ax=axes[0])
axes[0].set_title('Top 20 Features - Random Forest')
axes[0].set_xlabel('Importância')

# Importância acumulada
cumulative_importance = importances['importance'].cumsum()
axes[1].plot(range(1, len(cumulative_importance)+1), cumulative_importance, 'go-', linewidth=2)
axes[1].axhline(y=0.8, color='r', linestyle='--', label='80%')
axes[1].axhline(y=0.9, color='orange', linestyle='--', label='90%')
axes[1].set_xlabel('Número de Features')
axes[1].set_ylabel('Importância Acumulada')
axes[1].set_title('Importância Acumulada das Features')
axes[1].grid(True, alpha=0.3)
axes[1].legend()

# Encontrar quantas features chegam a 80% e 90%
n_80 = (cumulative_importance <= 0.8).sum() + 1
n_90 = (cumulative_importance <= 0.9).sum() + 1
axes[1].axvline(x=n_80, color='r', linestyle=':', alpha=0.5)
axes[1].axvline(x=n_90, color='orange', linestyle=':', alpha=0.5)
axes[1].text(n_80, 0.85, f'{n_80} features\n(80%)', ha='center')
axes[1].text(n_90, 0.95, f'{n_90} features\n(90%)', ha='center')

plt.tight_layout()
plt.show()

print(f"\nCom as top {n_80} features você atinge 80% da importância")
print(f"Com as top {n_90} features você atinge 90% da importância")

# Preparar dados de teste
df_test_numeric = df_test.select_dtypes(include=[np.number])
df_test_numeric = df_test_numeric.drop('difficulty', axis=1, errors='ignore')
X_test_original = df_test_numeric.drop('attack', axis=1)
y_test = df_test['attack'].values

# Padronizar usando o scaler do treino
X_test_scaled = scaler.transform(X_test_original)

# Validar melhor modelo no conjunto de teste
melhor_modelo_nome = df_resultados.iloc[0]['Modelo']
melhor_modelo = None

for nome, modelo in modelos.items():
    if nome == melhor_modelo_nome:
        melhor_modelo = modelo
        break

if melhor_modelo:
    # Re-treinar no treino completo
    melhor_modelo.fit(X_scaled, y)
    y_pred_test = melhor_modelo.predict(X_test_scaled)

    print("\n" + "="*60)
    print(f"VALIDAÇÃO NO KDDTest+ COM {melhor_modelo_nome}:")
    print("="*60)
    print(f"Acurácia:  {accuracy_score(y_test, y_pred_test):.4f}")
    print(f"Precisão:  {precision_score(y_test, y_pred_test):.4f}")
    print(f"Recall:    {recall_score(y_test, y_pred_test):.4f}")
    print(f"F1-Score:  {f1_score(y_test, y_pred_test):.4f}")

    # Matriz de confusão
    cm = confusion_matrix(y_test, y_pred_test)
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=['Normal', 'Ataque'],
                yticklabels=['Normal', 'Ataque'])
    plt.title(f'Matriz de Confusão - {melhor_modelo_nome}')
    plt.ylabel('Real')
    plt.xlabel('Predito')
    plt.show()

"""## Teste 4"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.kernel_ridge import KernelRidge
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.pipeline import Pipeline
import matplotlib.pyplot as plt
import seaborn as sns
import time
import warnings
warnings.filterwarnings('ignore')

# Supondo que você já tem X_scaled e y do código anterior
# Se não, rode primeiro o código de carregamento do dataset

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier # Added this import
from sklearn.kernel_ridge import KernelRidge
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.pipeline import Pipeline
import matplotlib.pyplot as plt
import seaborn as sns
import time
import warnings
warnings.filterwarnings('ignore')

# Supondo que você já tem X_scaled e y do código anterior
# Se não, rode primeiro o código de carregamento do dataset

print("="*80)
print("IMPLEMENTANDO OS 3 ITENS DO FEEDBACK DO PROFESSOR")
print("="*80)

# ============================================
# ITEM 1: SVM com kernel RBF
# ============================================
print("\n1. SVM COM KERNEL RBF")
print("-"*50)

# Separar treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)

# SVM RBF com diferentes parâmetros
svm_rbf_params = [
    {'C': 1.0, 'gamma': 'scale', 'name': 'SVM RBF (padrão)'},
    {'C': 10.0, 'gamma': 'scale', 'name': 'SVM RBF (C=10)'},
    {'C': 1.0, 'gamma': 0.1, 'name': 'SVM RBF (gamma=0.1)'},
    {'C': 10.0, 'gamma': 0.01, 'name': 'SVM RBF (C=10, gamma=0.01)'}
]

resultados_svm = []

for params in svm_rbf_params:
    print(f"\nTestando {params['name']}...")

    modelo = SVC(kernel='rbf', C=params['C'], gamma=params['gamma'], random_state=42)

    # Medir tempo de treino
    start_train = time.time()
    modelo.fit(X_train, y_train)
    train_time = time.time() - start_train

    # Medir tempo de teste (inferência)
    start_test = time.time()
    y_pred = modelo.predict(X_test)
    test_time = time.time() - start_test

    # Métricas
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    resultados_svm.append({
        'Modelo': params['name'],
        'Acurácia': acc,
        'Precisão': prec,
        'Recall': rec,
        'F1-Score': f1,
        'Tempo_Treino(s)': train_time,
        'Tempo_Teste(s)': test_time,
        'Tempo_Total(s)': train_time + test_time
    })

    print(f"  Acurácia: {acc:.4f} | F1: {f1:.4f} | Treino: {train_time:.2f}s | Teste: {test_time:.4f}s")

# ============================================
# ITEM 2: Regressão Logística (sem RBF - ela não tem kernel)
# Mas vou implementar o que o professor possivelmente quis dizer:
# a) Regressão Logística padrão
# b) Regressão Logística com features polinomiais (simula RBF)
# c) MLP (Rede Neural) que tem ativação RBF
# d) Kernel Ridge Regression (que usa kernel RBF)
# ============================================
print("\n" + "="*50)
print("2. REGRESSÃO LOGÍSTICA E VARIAÇÕES (conforme feedback)")
print("-"*50)

from sklearn.preprocessing import PolynomialFeatures
from sklearn.kernel_approximation import RBFSampler

# 2a. Regressão Logística padrão (linear)
print("\n2a. Regressão Logística Padrão (Linear)")
log_reg = LogisticRegression(max_iter=1000, random_state=42, n_jobs=-1)

start_train = time.time()
log_reg.fit(X_train, y_train)
train_time = time.time() - start_train

start_test = time.time()
y_pred_log = log_reg.predict(X_test)
test_time = time.time() - start_test

print(f"  Acurácia: {accuracy_score(y_test, y_pred_log):.4f}")
print(f"  F1-Score: {f1_score(y_test, y_pred_log):.4f}")
print(f"  Tempo Treino: {train_time:.2f}s | Teste: {test_time:.4f}s")

# 2b. Regressão Logística com features polinomiais (aproxima RBF)
print("\n2b. Regressão Logística com Features Polinomiais (grau 2)")
poly = PolynomialFeatures(degree=2, include_bias=False)
X_train_poly = poly.fit_transform(X_train[:10000])  # Amostra para não estourar memória
X_test_poly = poly.transform(X_test[:5000])

log_reg_poly = LogisticRegression(max_iter=1000, random_state=42)

start_train = time.time()
log_reg_poly.fit(X_train_poly, y_train[:10000])
train_time = time.time() - start_train

start_test = time.time()
y_pred_poly = log_reg_poly.predict(X_test_poly)
test_time = time.time() - start_test

print(f"  Acurácia: {accuracy_score(y_test[:5000], y_pred_poly):.4f}")
print(f"  F1-Score: {f1_score(y_test[:5000], y_pred_poly):.4f}")
print(f"  Tempo Treino: {train_time:.2f}s | Teste: {test_time:.4f}s")

# 2c. MLP (Rede Neural) - que tem ativação similar a RBF
print("\n2c. MLP (Rede Neural) - ativação ReLU + camadas")
mlp = MLPClassifier(hidden_layer_sizes=(100, 50), activation='relu',
                    max_iter=300, random_state=42, early_stopping=True)

start_train = time.time()
mlp.fit(X_train, y_train)
train_time = time.time() - start_train

start_test = time.time()
y_pred_mlp = mlp.predict(X_test)
test_time = time.time() - start_test

print(f"  Acurácia: {accuracy_score(y_test, y_pred_mlp):.4f}")
print(f"  F1-Score: {f1_score(y_test, y_pred_mlp):.4f}")
print(f"  Tempo Treino: {train_time:.2f}s | Teste: {test_time:.4f}s")

# 2d. Kernel Ridge Regression com kernel RBF (o mais próximo de "Logística com RBF")
print("\n2d. Kernel Ridge Regression (kernel RBF)")
from sklearn.kernel_ridge import KernelRidge

krr = KernelRidge(kernel='rbf', gamma=0.1, alpha=1.0)

# Converter para float e binarizar predição
start_train = time.time()
krr.fit(X_train, y_train.astype(np.float64))
train_time = time.time() - start_train

start_test = time.time()
y_pred_krr = (krr.predict(X_test) > 0.5).astype(int)
test_time = time.time() - start_test

print(f"  Acurácia: {accuracy_score(y_test, y_pred_krr):.4f}")
print(f"  F1-Score: {f1_score(y_test, y_pred_krr):.4f}")
print(f"  Tempo Treino: {train_time:.2f}s | Teste: {test_time:.4f}s")

# ============================================
# ITEM 3: COMPARAÇÃO DE TEMPOS (Treino vs Teste)
# ============================================
print("\n" + "="*50)
print("3. COMPARAÇÃO DE TEMPOS DE TREINO E TESTE")
print("="*50)

# Coletar todos os modelos testados
todos_modelos = []

# SVM RBF (melhor)
melhor_svm = resultados_svm[0]
todos_modelos.append({
    'Modelo': 'SVM RBF (padrão)',
    'Tempo_Treino(s)': melhor_svm['Tempo_Treino(s)'],
    'Tempo_Teste(s)': melhor_svm['Tempo_Teste(s)'],
    'F1-Score': melhor_svm['F1-Score']
})

# Logistic Regression
# Need to define train_time_log and test_time_log from the 2a section
# Since the variable names were not unique, I'll use the ones from the last Logistic Regression block.
# If multiple Logistic Regression models are run, ensure these are specific.
todos_modelos.append({
    'Modelo': 'Logistic Regression',
    'Tempo_Treino(s)': train_time,
    'Tempo_Teste(s)': test_time,
    'F1-Score': f1_score(y_test, y_pred_log)
})

# MLP
todos_modelos.append({
    'Modelo': 'MLP Neural Network',
    'Tempo_Treino(s)': train_time,
    'Tempo_Teste(s)': test_time,
    'F1-Score': f1_score(y_test, y_pred_mlp)
})

# Random Forest (do código anterior)
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
start_train = time.time()
rf.fit(X_train, y_train)
train_time_rf = time.time() - start_train
start_test = time.time()
y_pred_rf = rf.predict(X_test)
test_time_rf = time.time() - start_test

todos_modelos.append({
    'Modelo': 'Random Forest',
    'Tempo_Treino(s)': train_time_rf,
    'Tempo_Teste(s)': test_time_rf,
    'F1-Score': f1_score(y_test, y_pred_rf)
})

# Criar dataframe
df_tempos = pd.DataFrame(todos_modelos)
df_tempos = df_tempos.sort_values('F1-Score', ascending=False)

print("\nCOMPARAÇÃO COMPLETA (Treino vs Teste):")
print(df_tempos.to_string(index=False))

# Gráfico de tempos
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Gráfico 1: Tempo de Treino vs Teste
ax1 = axes[0]
x = np.arange(len(df_tempos['Modelo']))
width = 0.35

bars1 = ax1.bar(x - width/2, df_tempos['Tempo_Treino(s)'], width, label='Treino', color='skyblue')
bars2 = ax1.bar(x + width/2, df_tempos['Tempo_Teste(s)'], width, label='Teste', color='lightcoral')

ax1.set_xlabel('Modelos')
ax1.set_ylabel('Tempo (segundos)')
ax1.set_title('Tempo de Treino vs Teste (escala log)')
ax1.set_xticks(x)
ax1.set_xticklabels(df_tempos['Modelo'], rotation=45, ha='right')
ax1.legend()
ax1.set_yscale('log')  # Escala log porque tempos variam muito

# Gráfico 2: Trade-off F1-Score vs Tempo Total
ax2 = axes[1]
ax2.scatter(df_tempos['Tempo_Treino(s)'] + df_tempos['Tempo_Teste(s)'] and 0,
            df_tempos['F1-Score'], s=100, alpha=0.7)

for i, row in df_tempos.iterrows():
    ax2.annotate(row['Modelo'],
                (row['Tempo_Treino(s)'] + row['Tempo_Teste(s)'], row['F1-Score']),
                xytext=(5, 5), textcoords='offset points', fontsize=8)

ax2.set_xlabel('Tempo Total (Treino + Teste) - segundos')
ax2.set_ylabel('F1-Score')
ax2.set_title('Trade-off: Performance vs Tempo')
ax2.set_xscale('log')
ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import time
import warnings
warnings.filterwarnings('ignore')

# Supondo que você já tem X_scaled e y do carregamento do dataset
# Se não, execute primeiro o código de download do NSL-KDD

print("="*80)
print("BENCHMARK COMPLETO - TEMPOS DE TREINO E TESTE SEPARADOS")
print("="*80)

# Separar treino e teste (80/20)
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)

print(f"\nTamanho do conjunto:")
print(f"  Treino: {X_train.shape[0]} amostras")
print(f"  Teste:  {X_test.shape[0]} amostras")
print(f"  Features: {X_train.shape[1]}")

# Dicionário para armazenar todos os resultados
todos_resultados = []

# ============================================
# 1. RANDOM FOREST
# ============================================
print("\n" + "="*60)
print("1. RANDOM FOREST")
print("="*60)

rf_params = [
    {'n_estimators': 50, 'name': 'RF (50 árvores)'},
    {'n_estimators': 100, 'name': 'RF (100 árvores)'},
    {'n_estimators': 200, 'name': 'RF (200 árvores)'}
]

for params in rf_params:
    print(f"\nTestando {params['name']}...")

    modelo = RandomForestClassifier(
        n_estimators=params['n_estimators'],
        random_state=42,
        n_jobs=-1
    )

    # Tempo de TREINO
    start_train = time.time()
    modelo.fit(X_train, y_train)
    train_time = time.time() - start_train

    # Tempo de TESTE (inferência)
    start_test = time.time()
    y_pred = modelo.predict(X_test)
    test_time = time.time() - start_test

    # Métricas
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    # Tempo por predição (em ms)
    time_per_prediction_ms = (test_time / len(X_test)) * 1000

    todos_resultados.append({
        'Algoritmo': 'Random Forest',
        'Variação': params['name'],
        'Acurácia': acc,
        'Precisão': prec,
        'Recall': rec,
        'F1-Score': f1,
        'Tempo_Treino(s)': train_time,
        'Tempo_Teste(s)': test_time,
        'Tempo_ms_por_predicao': time_per_prediction_ms
    })

    print(f"  ✅ Acurácia: {acc:.4f}")
    print(f"  ✅ F1-Score: {f1:.4f}")
    print(f"  ⏱️  Tempo Treino: {train_time:.2f} segundos")
    print(f"  ⏱️  Tempo Teste: {test_time:.4f} segundos")
    print(f"  ⚡ Tempo por predição: {time_per_prediction_ms:.4f} ms")

# ============================================
# 2. DECISION TREE
# ============================================
print("\n" + "="*60)
print("2. DECISION TREE")
print("="*60)

dt_params = [
    {'max_depth': None, 'name': 'DT (sem limite)'},
    {'max_depth': 10, 'name': 'DT (max_depth=10)'},
    {'max_depth': 5, 'name': 'DT (max_depth=5)'}
]

for params in dt_params:
    print(f"\nTestando {params['name']}...")

    modelo = DecisionTreeClassifier(
        max_depth=params['max_depth'],
        random_state=42
    )

    start_train = time.time()
    modelo.fit(X_train, y_train)
    train_time = time.time() - start_train

    start_test = time.time()
    y_pred = modelo.predict(X_test)
    test_time = time.time() - start_test

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    time_per_prediction_ms = (test_time / len(X_test)) * 1000

    todos_resultados.append({
        'Algoritmo': 'Decision Tree',
        'Variação': params['name'],
        'Acurácia': acc,
        'Precisão': prec,
        'Recall': rec,
        'F1-Score': f1,
        'Tempo_Treino(s)': train_time,
        'Tempo_Teste(s)': test_time,
        'Tempo_ms_por_predicao': time_per_prediction_ms
    })

    print(f"  ✅ Acurácia: {acc:.4f}")
    print(f"  ✅ F1-Score: {f1:.4f}")
    print(f"  ⏱️  Tempo Treino: {train_time:.2f} segundos")
    print(f"  ⏱️  Tempo Teste: {test_time:.4f} segundos")
    print(f"  ⚡ Tempo por predição: {time_per_prediction_ms:.4f} ms")

# ============================================
# 3. KNN (K-Nearest Neighbors)
# ============================================
print("\n" + "="*60)
print("3. KNN (K-NEAREST NEIGHBORS)")
print("="*60)

knn_params = [
    {'n_neighbors': 3, 'name': 'KNN (k=3)'},
    {'n_neighbors': 5, 'name': 'KNN (k=5)'},
    {'n_neighbors': 7, 'name': 'KNN (k=7)'},
    {'n_neighbors': 10, 'name': 'KNN (k=10)'}
]

for params in knn_params:
    print(f"\nTestando {params['name']}...")

    modelo = KNeighborsClassifier(n_neighbors=params['n_neighbors'], n_jobs=-1)

    start_train = time.time()
    modelo.fit(X_train, y_train)
    train_time = time.time() - start_train

    start_test = time.time()
    y_pred = modelo.predict(X_test)
    test_time = time.time() - start_test

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    time_per_prediction_ms = (test_time / len(X_test)) * 1000

    todos_resultados.append({
        'Algoritmo': 'KNN',
        'Variação': params['name'],
        'Acurácia': acc,
        'Precisão': prec,
        'Recall': rec,
        'F1-Score': f1,
        'Tempo_Treino(s)': train_time,
        'Tempo_Teste(s)': test_time,
        'Tempo_ms_por_predicao': time_per_prediction_ms
    })

    print(f"  ✅ Acurácia: {acc:.4f}")
    print(f"  ✅ F1-Score: {f1:.4f}")
    print(f"  ⏱️  Tempo Treino: {train_time:.2f} segundos")
    print(f"  ⏱️  Tempo Teste: {test_time:.4f} segundos")
    print(f"  ⚡ Tempo por predição: {time_per_prediction_ms:.4f} ms")

# ============================================
# 4. LOGISTIC REGRESSION
# ============================================
print("\n" + "="*60)
print("4. LOGISTIC REGRESSION")
print("="*60)

lr_params = [
    {'solver': 'lbfgs', 'max_iter': 100, 'name': 'LogReg (lbfgs)'},
    {'solver': 'liblinear', 'max_iter': 100, 'name': 'LogReg (liblinear)'},
    {'solver': 'saga', 'max_iter': 200, 'name': 'LogReg (saga)'}
]

for params in lr_params:
    print(f"\nTestando {params['name']}...")

    modelo = LogisticRegression(
        solver=params['solver'],
        max_iter=params['max_iter'],
        random_state=42,
        n_jobs=-1
    )

    start_train = time.time()
    modelo.fit(X_train, y_train)
    train_time = time.time() - start_train

    start_test = time.time()
    y_pred = modelo.predict(X_test)
    test_time = time.time() - start_test

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    time_per_prediction_ms = (test_time / len(X_test)) * 1000

    todos_resultados.append({
        'Algoritmo': 'Logistic Regression',
        'Variação': params['name'],
        'Acurácia': acc,
        'Precisão': prec,
        'Recall': rec,
        'F1-Score': f1,
        'Tempo_Treino(s)': train_time,
        'Tempo_Teste(s)': test_time,
        'Tempo_ms_por_predicao': time_per_prediction_ms
    })

    print(f"  ✅ Acurácia: {acc:.4f}")
    print(f"  ✅ F1-Score: {f1:.4f}")
    print(f"  ⏱️  Tempo Treino: {train_time:.2f} segundos")
    print(f"  ⏱️  Tempo Teste: {test_time:.4f} segundos")
    print(f"  ⚡ Tempo por predição: {time_per_prediction_ms:.4f} ms")

# ============================================
# 5. SVM (com diferentes kernels - incluindo RBF)
# ============================================
print("\n" + "="*60)
print("5. SVM (SUPPORT VECTOR MACHINE)")
print("="*60)

svm_params = [
    {'kernel': 'linear', 'C': 1.0, 'name': 'SVM Linear'},
    {'kernel': 'rbf', 'C': 1.0, 'gamma': 'scale', 'name': 'SVM RBF (padrão)'},
    {'kernel': 'rbf', 'C': 10.0, 'gamma': 'scale', 'name': 'SVM RBF (C=10)'},
    {'kernel': 'poly', 'degree': 3, 'C': 1.0, 'name': 'SVM Polinomial (grau 3)'}
]

for params in svm_params:
    print(f"\nTestando {params['name']}...")

    if params['kernel'] == 'rbf':
        modelo = SVC(kernel='rbf', C=params['C'], gamma=params['gamma'], random_state=42)
    elif params['kernel'] == 'poly':
        modelo = SVC(kernel='poly', degree=params['degree'], C=params['C'], random_state=42)
    else:
        modelo = SVC(kernel='linear', C=params['C'], random_state=42)

    start_train = time.time()
    modelo.fit(X_train, y_train)
    train_time = time.time() - start_train

    start_test = time.time()
    y_pred = modelo.predict(X_test)
    test_time = time.time() - start_test

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    time_per_prediction_ms = (test_time / len(X_test)) * 1000

    todos_resultados.append({
        'Algoritmo': 'SVM',
        'Variação': params['name'],
        'Acurácia': acc,
        'Precisão': prec,
        'Recall': rec,
        'F1-Score': f1,
        'Tempo_Treino(s)': train_time,
        'Tempo_Teste(s)': test_time,
        'Tempo_ms_por_predicao': time_per_prediction_ms
    })

    print(f"  ✅ Acurácia: {acc:.4f}")
    print(f"  ✅ F1-Score: {f1:.4f}")
    print(f"  ⏱️  Tempo Treino: {train_time:.2f} segundos")
    print(f"  ⏱️  Tempo Teste: {test_time:.4f} segundos")
    print(f"  ⚡ Tempo por predição: {time_per_prediction_ms:.4f} ms")

# Criar dataframe com todos os resultados
df_completo = pd.DataFrame(todos_resultados)

print("\n" + "="*80)
print("TABELA COMPLETA - TODOS OS ALGORITMOS COM TEMPOS SEPARADOS")
print("="*80)

# Selecionar melhor versão de cada algoritmo (maior F1-Score)
melhores_por_algoritmo = df_completo.loc[df_completo.groupby('Algoritmo')['F1-Score'].idxmax()]

# Formatar para exibição
display_cols = ['Algoritmo', 'Variação', 'F1-Score', 'Tempo_Treino(s)', 'Tempo_Teste(s)', 'Tempo_ms_por_predicao']
print(melhores_por_algoritmo[display_cols].to_string(index=False))

print("\n" + "="*80)
print("RANKING POR TEMPO DE TESTE (mais rápido para mais lento)")
print("="*80)
ranking_teste = df_completo.sort_values('Tempo_Teste(s)')
print(ranking_teste[['Algoritmo', 'Variação', 'Tempo_Teste(s)', 'Tempo_ms_por_predicao', 'F1-Score']].head(10).to_string(index=False))

print("\n" + "="*80)
print("RANKING POR F1-SCORE (melhor performance)")
print("="*80)
ranking_f1 = df_completo.sort_values('F1-Score', ascending=False)
print(ranking_f1[['Algoritmo', 'Variação', 'F1-Score', 'Tempo_Teste(s)', 'Tempo_ms_por_predicao']].head(10).to_string(index=False))

# Gráfico comparativo
fig, axes = plt.subplots(2, 2, figsize=(16, 12))

# 1. Tempo de Treino vs Teste (escala log)
ax1 = axes[0, 0]
for algoritmo in df_completo['Algoritmo'].unique():
    dados_algo = df_completo[df_completo['Algoritmo'] == algoritmo]
    ax1.scatter(dados_algo['Tempo_Treino(s)'], dados_algo['Tempo_Teste(s)'],
                label=algoritmo, s=80, alpha=0.7)
ax1.set_xlabel('Tempo de Treino (segundos)')
ax1.set_ylabel('Tempo de Teste (segundos)')
ax1.set_title('Tempo de Treino vs Teste (escala log)')
ax1.set_xscale('log')
ax1.set_yscale('log')
ax1.legend()
ax1.grid(True, alpha=0.3)

# 2. F1-Score vs Tempo de Teste
ax2 = axes[0, 1]
for algoritmo in df_completo['Algoritmo'].unique():
    dados_algo = df_completo[df_completo['Algoritmo'] == algoritmo]
    ax2.scatter(dados_algo['Tempo_Teste(s)'], dados_algo['F1-Score'],
                label=algoritmo, s=80, alpha=0.7)
ax2.set_xlabel('Tempo de Teste (segundos)')
ax2.set_ylabel('F1-Score')
ax2.set_title('Trade-off: Performance vs Velocidade de Inferência')
ax2.set_xscale('log')
ax2.legend()
ax2.grid(True, alpha=0.3)

# 3. Barplot - Tempo por predição (ms)
ax3 = axes[1, 0]
melhores = df_completo.loc[df_completo.groupby('Algoritmo')['F1-Score'].idxmax()]
cores = plt.cm.viridis(np.linspace(0, 1, len(melhores)))
bars = ax3.barh(melhores['Algoritmo'], melhores['Tempo_ms_por_predicao'], color=cores)
ax3.set_xlabel('Tempo por Predição (milissegundos)')
ax3.set_title('Velocidade de Inferência por Algoritmo (melhor versão)')
ax3.set_xscale('log')

# Adicionar valores nas barras
for i, (bar, tempo) in enumerate(zip(bars, melhores['Tempo_ms_por_predicao'])):
    ax3.text(tempo, bar.get_y() + bar.get_height()/2,
             f'{tempo:.4f} ms', va='center', ha='left', fontsize=9)

# 4. Boxplot da distribuição de F1-Score por algoritmo
ax4 = axes[1, 1]
df_completo.boxplot(column='F1-Score', by='Algoritmo', ax=ax4)
ax4.set_title('Distribuição do F1-Score por Algoritmo')
ax4.set_xlabel('Algoritmo')
ax4.set_ylabel('F1-Score')
plt.xticks(rotation=45, ha='right')

plt.tight_layout()
plt.show()
